
<div class="dashboard">
	<div class="quick-action">
		<h2>Quick actions</h2>
		
		<a class="articles" href="/admin/articles/new">
			<span class="icon">&nbsp;</span>
			<h3>Add article</h3>
		</a>
		
		<a href="/admin/pages/new" class="pages">
			<span class="icon">&nbsp;</span>
			<h3>Add page</h3>
		</a>
		
		<a href="/admin/store" class="store">
			<span class="icon">&nbsp;</span>
			<h3>Manage store</h3>
		</a>
		
		<a href="/admin/settings" class="settings">
			<span class="icon">&nbsp;</span>
			<h3>Settings</h3>
		</a>
	</div>
	
	<div class="reports">
		<h2>Reports</h2>
		
	
	</div>
</div>

<?php echo $this->sidebar; ?>