<form action="<?php echo $this->escape($this->element->getAction()); ?>" 
      method="<?php echo $this->escape($this->element->getMethod()); ?>"
      name="<?php echo $this->escape($this->element->getName());?>"
      id="<?php echo $this->escape($this->element->getAttrib('id'));?>"
      class="<?php echo $this->escape($this->element->getAttrib('class'));?>">
      
    <div class="submit">
    	<h1>Add new Article</h1>
    	<?php echo $this->element->submitButton; ?>
	</div>

	<div class="fields">
    <div>
    <label for="title">Title :</label>
    <?php echo $this->element->title;?>
    </div>
    
    <div>
    <label for="language">Language :</label>
    <?php echo $this->element->language; ?>
    </div>
    
    <div>
    <label for="featured">Featured article :</label>
    <?php echo $this->element->featured; ?>
    </div>
    
    <div>
    <label for="status">Status :</label>
    <?php echo $this->element->status; ?>
    </div>
    
    <div>
    <label for="beginDate">Date :</label>
    <?php echo $this->element->beginDate; ?>
    </div>
    
    <div>
    <label for="description">Description :</label>
    <?php echo $this->element->description; ?>
    </div>
    
	</div>
</form>