<div>
<form action="<?php echo $this->escape($this->element->getAction()); ?>" 
      method="<?php echo $this->escape($this->element->getMethod()); ?>"
      name="<?php echo $this->escape($this->element->getName());?>"
      id="<?php echo $this->escape($this->element->getAttrib('id'));?>"
      class="<?php echo $this->escape($this->element->getAttrib('class'));?>">
    <div class="confirm-delete" id="confirm-delete">
   Are you sure you want to delete this?
    </div>
    <div class="submit" id="submit-btn">
        <?php echo $this->element->yes; ?>
        <?php echo $this->element->no; ?>
    </div>

</form>
</div>