<div id="message_box">
     <?php if(!empty($this->messages[0])) echo $this->messages[0]; ?>
</div>

<h1>Featured articles</h1>
<table>
    <thead>
        <tr>
            <td>Title</td>
            <td>Date</td>
            <td>Featured article</td>
            <td>Status</td>
            <td>Created by</td>
            <td>Language</td>
            <td>Edit / Delete</td>
        </tr>
    </thead>
    <tbody>
       <?php if($this->articles) { ?>
        <?php foreach ($this->articles as $key) { ?>
        <tr>
            <td><?php echo $this->escape($key->getTitle()); ?></td>
            <td><?php $date = new Zend_Date(strtotime($this->escape($key->getDate())), false, 'en'); echo $this->escape($date->toString()); ?></td>
            <td><?php if($this->escape($key->getFeatured()) == 1) { echo 'Yes'; } else { echo 'No'; } ?></td>
            <td><?php if($this->escape($key->getStatus()) == 1) { echo 'Enabled'; } else { echo 'Disabled'; } ?></td>
            <td><?php $userData = $this->userData->getRowById($key->getCreatedby()); echo $this->escape($userData[0]->getName()) . ' ' . $this->escape($userData[0]->getLastname()); ?></td>
            <td><?php $lang = $this->lang->getRowById($key->getLang()); echo $this->escape($lang[0]->getLang()); ?></td>
            <td><?php $this->editForm->getElement('id')->setValue($this->escape($key->getId())); echo $this->editForm; ?>
                <?php $this->deleteForm->getElement('id')->setValue($this->escape($key->getId())); echo $this->deleteForm; ?></td>
        </tr>
        <?php } ?>
        <?php } ?>
    </tbody>
</table>

<?php 
if($this->pageNum > 1){
echo $this->paginationControl($this->articles,'Sliding', 'pagination.phtml'); 
}?>


<script type = "text/javascript">

    var url='<?php echo $this->escape(Zend_Controller_Front::getInstance()->getBaseUrl());?>'+'/admin/articles/delete';
$('#delete').submit(function() {
var id = $(this).find("input:hidden").val();

	   var answer = confirm("Are you sure you want to delete this article?");
if (answer){	

        
	$.post(url, {id: id, del: 'Yes'}, function(data){
		        alert('Article successfully deleted.');
		       window.location.reload();
		         
			
		
	});
}
return false;
	});

</script>