<div id="message_box">
     <?php if(!empty($this->messages[0])) echo $this->messages[0]; ?>
</div>

<h1>Products</h1>
<table>
    <thead>
        <tr>
            <td>Name</td>
            <td>Status</td>
            <td>Created by</td>
            <td>Short description</td>
            <td>Category</td>
            <td>Edit / Delete</td>
        </tr>
    </thead>
    <tbody>
       <?php if($this->products) { ?>
        <?php foreach ($this->products as $key) { ?>
        <tr>
            <td><?php echo $this->escape($key->getName()); ?></td>
            <td><?php if($this->escape($key->getStatus()) == 1) { echo 'Enabled'; } else { echo 'Disabled'; } ?></td>
            <td><?php $userData = $this->userData->getRowById($key->getCreatedby()); echo $this->escape($userData[0]->getName()) . ' ' . $this->escape($userData[0]->getLastname()); ?></td>
            <td><?php echo $this->escape($key->getShort_desc()); ?></td>
            <td>
                <?php $categories = $this->category->getAllCategoriesByProductId($key->getId()); ?>
                <?php $category = ''; ?>
                <?php foreach ($categories as $key2) { ?>
                <?php $category .= $key2->getTitle(); ?>
                <?php $category .= ', '; ?>
                <?php } ?>
                <?php echo rtrim($category, ', '); ?>
                
            </td>
            <td><?php $lang = $this->lang->getRowById($key->getLang()); echo $this->escape($lang[0]->getLang()); ?></td>
            <td><?php $this->editForm->getElement('id')->setValue($this->escape($key->getId())); echo $this->editForm; ?>
                <?php $this->deleteForm->getElement('id')->setValue($this->escape($key->getId())); echo $this->deleteForm; ?>
            </td>
        </tr>
        <?php } ?>
        <?php } ?>
    </tbody>
</table>

<?php 
if($this->pageNum > 1){

echo $this->paginationControl($this->products,'Sliding', 'pagination.phtml'); 
}?>


<script type = "text/javascript">

    var url='<?php echo $this->escape(Zend_Controller_Front::getInstance()->getBaseUrl());?>'+'/admin/products/deleteproduct';
$('#delete').submit(function() {
var id = $(this).find("input:hidden").val();

	   var answer = confirm("Are you sure you want to delete this product?")
if (answer){	

        
	$.post(url, {id: id, del: 'Yes'}, function(data){
            
          
            var message = $.trim($(".error", data).text());
            if($($(".error", data)).length > 0){
             var message = $.trim($(".error", data).text());
        } else
            {
                var message = $.trim($("#message_box", data).text());
            }
            
            alert(message);
        
                    window.location.reload();
		         
			
		
	});
}
return false;
	});

</script>