<div class="store">
	<div class="quick-action">
		<h2>Quick actions</h2>
		
		<a class="new-prod" href="/admin/products/new">
			<span class="icon">&nbsp;</span>
			<h3>Add new product</h3>
		</a>
		
		<a href="/admin/pages/featured" class="feat-prod">
			<span class="icon">&nbsp;</span>
			<h3>Featured products</h3>
		</a>
		
		<a href="/admin/categories/new" class="new-cat">
			<span class="icon">&nbsp;</span>
			<h3>Add new category</h3>
		</a>
		
		<a href="/admin/categories" class="cats">
			<span class="icon">&nbsp;</span>
			<h3>Show Categories</h3>
		</a>
	</div>
	
</div>
