<?php echo $this->errorMessage; ?>
<?php echo $this->form; ?>

<?php if($this->images) { ?>
<table>
    <thead>
        <tr>
            <td>Image</td>
            <td>Delete</td>
        </tr>
    </thead>
    <tbody>
        
            <?php foreach ($this->images as $key) { ?>
             <tr>
                 <td><img src="<?php echo $this->imagePath . $key->getImg(); ?>"></td>
                 <td><?php $this->deleteForm->getElement('id')->setValue($this->escape($key->getId())); echo $this->deleteForm; ?></td>
             </tr>
           <?php } ?>
    </tbody>
</table>

<?php } ?>


<script type = "text/javascript">

    var url='<?php echo $this->escape(Zend_Controller_Front::getInstance()->getBaseUrl());?>'+'/admin/categories/deleteimage';
$('#delete').submit(function() {
var id = $(this).find("input:hidden").val();

	   var answer = confirm("Are you sure you want to delete this image?");
if (answer){	

        
	$.post(url, {id: id, del: 'Yes'}, function(data){
		        alert('Image successfully deleted.');
		       window.location.reload();
		         
			
		
	});
}
return false;
	});

</script>