<?php echo $this->errorMessage; ?>
<?php echo $this->langForm; ?>
<?php echo $this->form; ?>

<?php if($this->webImage || $this->mailImage) { ?>
<table>
    <thead>
        <tr>
            <td>Image</td>
            <td>Delete</td>
        </tr>
    </thead>
    <tbody>
        
            <?php foreach ($this->webImage as $key) { ?>
             <tr>
                 <td><img src="<?php echo $this->imagePath . $key->getImg(); ?>"></td>
                 <td><?php $this->deleteForm->getElement('id')->setValue($this->escape($key->getId())); echo $this->deleteForm; ?></td>
             </tr>
           <?php } ?>
             <?php foreach ($this->mailImage as $key) { ?>
             <tr>
                 <td><img src="<?php echo $this->imagePath . $key->getImg(); ?>"></td>
                 <td><?php $this->deleteForm->getElement('id')->setValue($this->escape($key->getId())); echo $this->deleteForm; ?></td>
             </tr>
           <?php } ?>
    </tbody>
</table>

<?php } ?>