<div class="dashboard">
	<div class="quick-action">
		<h2>Quick actions</h2>
		
		<a class="general" href="/admin/settings/general">
			<span class="icon">&nbsp;</span>
			<h3>General Settings</h3>
		</a>
		
		<a href="/admin/settings/modules" class="mods">
			<span class="icon">&nbsp;</span>
			<h3>Modules</h3>
		</a>
		
		<a href="/admin/settings/contact" class="cntct">
			<span class="icon">&nbsp;</span>
			<h3>Contact data</h3>
		</a>
		
		<a href="/admin/settings/users" class="users">
			<span class="icon">&nbsp;</span>
			<h3>Manage users</h3>
		</a>
		
	</div>
	
</div>