<form action="<?php echo $this->escape($this->element->getAction()); ?>" 
      method="<?php echo $this->escape($this->element->getMethod()); ?>"
      name="<?php echo $this->escape($this->element->getName());?>"
      id="<?php echo $this->escape($this->element->getAttrib('id'));?>"
      class="<?php echo $this->escape($this->element->getAttrib('class'));?>"
      enctype="<?php echo $this->escape($this->element->getAttrib('enctype'));?>">
      
	<div class="submit-new">
	<h1>Add new Setting loadout</h1>
    	<?php echo $this->element->submitButton; ?>
	</div>
	<div class="fields">
    <div>
    <label for="title">Title :</label>
    <?php echo $this->element->title;?>
    </div>
    
    <div>
    <label for="language">Language :</label>
    <?php echo $this->element->language; ?>
    </div>
    
    <div>
    <label for="meta_keywords">Meta keywords :</label>
    <?php echo $this->element->meta_keywords; ?>
    </div> 
            
    <div>
    <label for="meta_description">Meta Description :</label>
    <?php echo $this->element->meta_description; ?>
    </div>
  
    <?php if(isset($this->element->contacts) && !empty ($this->element->contacts)) { ?>
    <div>
    <label for="contacts">Contact information :</label>
    <?php echo $this->element->contacts; ?>
    </div>
    <?php } ?> 
            
    <div>
    <label for="file">Web logo upload :</label>
    <?php echo $this->element->file; ?>
    </div>
            
    <div>
    <label for="file2">Mail logo upload :</label>
    <?php echo $this->element->file2; ?>
    </div>
    
	</div>
</form>