<!doctype html>
<html>
<head>
<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
<title>SMB | Admin</title>
<?php  echo $this->headLink()->appendStylesheet($this->baseUrl().'/skin/admin/css/style.css');?>
</head>
<body>

	<div class="login-area">
		<div class="wrap">
			<div class="smb">
				<div class="logo"></div>
				<small>simple modern booking - system admin area</small>
			</div>
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
	
</body>
</html>