<!doctype html>
<html>
<head>
<?php  $this->jQuery()->enable()
            ->setVersion('1.8');
        echo $this->jQuery(); ?>
<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
<title>SMB | Admin</title>
<?php  echo $this->headLink()->appendStylesheet($this->baseUrl().'/skin/admin/css/style.css'); ?>
</head>

<body>
	<div class="admin-wrapper">
		<div class="header">
			<div class="logo">
				<a href="/admin/index/dashboard">SMB</a>
			</div>
			
			<div class="user-nav">
				<ul>
					<li><a class="profile" href="#">Profile</a></li>
					<li><a class="logout" href="/admin/index/logout">Logout</a></li>
				</ul>
			</div>
			<div class="welcome">
				<p>
					Welcome, <a href="#"><?php echo Zend_Auth::getInstance()->getIdentity()->email;?></a>
				</p>
			</div>
		</div>
		<div class="main">
			
			<div class="nav">
				<?php echo $this->navigation()->menu();?>
			</div>
			
			
			<div class = "content">
			
			<?php echo $this->layout()->content; ?>
			</div>
			
			<?php echo $this->placeholder('sidebar'); ?>
		</div>
		
		
	</div>
	<div class="footer">
			<div class="copy">&copy; PROODOS j.d.o.o. 2013</div>
	</div>
</body>
</html>