<form action="<?php echo $this->escape($this->element->getAction()); ?>" 
      method="<?php echo $this->escape($this->element->getMethod()); ?>"
      name="<?php echo $this->escape($this->element->getName());?>"
      id="<?php echo $this->escape($this->element->getAttrib('id'));?>"
      class="<?php echo $this->escape($this->element->getAttrib('class'));?>"
      enctype="<?php echo $this->escape($this->element->getAttrib('enctype'));?>">
      
	<div class="submit-new">
	<h1>Add new Category</h1>
    	<?php echo $this->element->submitButton; ?>
	</div>
	<div class="fields">
    <div>
    <label for="title">Title :</label>
    <?php echo $this->element->title;?>
    </div>
    
    <div>
    <label for="language">Language :</label>
    <?php echo $this->element->language; ?>
    </div>
    
    <div>
    <label for="status">Status :</label>
    <?php echo $this->element->status; ?>
    </div>
  
    <div>
    <label for="short">Short description :</label>
    <?php echo $this->element->short; ?>
    </div>
   
    <div>
    <label for="description">Description :</label>
    <?php echo $this->element->description; ?>
    </div>
    
     <div>
    <label for="products">Products :</label>
    <?php echo $this->element->products; ?>
    </div>
    
    <div>
    <label for="file">Images upload :</label>
    <?php echo $this->element->file; ?>
    </div>
    
	</div>
</form>