<form action="<?php echo $this->escape($this->element->getAction()); ?>" 
      method="<?php echo $this->escape($this->element->getMethod()); ?>"
      name="<?php echo $this->escape($this->element->getName());?>"
      id="<?php echo $this->escape($this->element->getAttrib('id'));?>"
      class="<?php echo $this->escape($this->element->getAttrib('class'));?>">
   
<div>
    <?php echo $this->element->id; ?>
</div>
    
<div class="submit">
    <?php echo $this->element->submitButton; ?>
</div>
</form>